# Generated by Django 3.0.6 on 2020-05-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='psw',
            field=models.TextField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
