# Generated by Django 3.0.6 on 2020-05-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_post_psw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='psw',
            field=models.CharField(max_length=20),
        ),
    ]
