# Generated by Django 3.0.6 on 2020-05-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20200507_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='post',
            name='psw',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
