# Generated by Django 3.0.6 on 2020-05-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20200507_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='psw',
        ),
    ]
