# Generated by Django 3.0.6 on 2020-05-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_remove_post_psw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
