# Generated by Django 3.0.6 on 2020-05-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_auto_20200509_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.ImageField(default='', upload_to='img'),
            preserve_default=False,
        ),
    ]
