# Generated by Django 3.0.6 on 2020-05-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_post_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img_url',
        ),
    ]
